# Bipolar BAM to recognize letters

In [1]:
import numpy as np

Store three letters A, B, C using 5x3 matrix using bipolar codes

In [7]:
A = [[-1,1,1],
    [1,-1,-1],
    [1,1,1],
    [1,-1,1],
    [1,-1,1]]
A = np.array(A)

In [9]:
B = [[1,1,1],
    [1,-1,1],
    [1,1,1],
    [1,-1,1],
    [1,1,1]]
B = np.array(B)

In [10]:
C = [[1,1,1],
    [1,-1,-1],
    [1,-1,-1],
    [1,-1,-1],
    [1,1,1]]
C = np.array(C)

In [39]:
t1 = np.array([[1,-1,-1]])
t2 = np.array([[-1,1,-1]])
t3 = np.array([[-1,-1,1]])

In [11]:
flat_a = A.flatten()
flat_b = B.flatten()
flat_c = C.flatten()

In [28]:
flat_a = np.array([flat_a])

In [29]:
flat_a.shape

(1, 15)

In [30]:
flat_a

array([[-1,  1,  1,  1, -1, -1,  1,  1,  1,  1, -1,  1,  1, -1,  1]])

In [31]:
flat_b = np.array([flat_b])

In [32]:
flat_c = np.array([flat_c])

In [33]:
trans_a = np.transpose(flat_a)

In [43]:
trans_b = np.transpose(flat_b)
trans_c = np.transpose(flat_c)

In [35]:
trans_a.shape

(15, 1)

In [40]:
t1.shape

(1, 3)

In [41]:
w1 = np.matmul(trans_a,t1)

In [44]:
w2 = np.matmul(trans_b,t2)
w3 = np.matmul(trans_c,t3)

In [45]:
w1

array([[-1,  1,  1],
       [ 1, -1, -1],
       [ 1, -1, -1],
       [ 1, -1, -1],
       [-1,  1,  1],
       [-1,  1,  1],
       [ 1, -1, -1],
       [ 1, -1, -1],
       [ 1, -1, -1],
       [ 1, -1, -1],
       [-1,  1,  1],
       [ 1, -1, -1],
       [ 1, -1, -1],
       [-1,  1,  1],
       [ 1, -1, -1]])

In [46]:
w2

array([[-1,  1, -1],
       [-1,  1, -1],
       [-1,  1, -1],
       [-1,  1, -1],
       [ 1, -1,  1],
       [-1,  1, -1],
       [-1,  1, -1],
       [-1,  1, -1],
       [-1,  1, -1],
       [-1,  1, -1],
       [ 1, -1,  1],
       [-1,  1, -1],
       [-1,  1, -1],
       [-1,  1, -1],
       [-1,  1, -1]])

In [47]:
w3

array([[-1, -1,  1],
       [-1, -1,  1],
       [-1, -1,  1],
       [-1, -1,  1],
       [ 1,  1, -1],
       [ 1,  1, -1],
       [-1, -1,  1],
       [ 1,  1, -1],
       [ 1,  1, -1],
       [-1, -1,  1],
       [ 1,  1, -1],
       [ 1,  1, -1],
       [-1, -1,  1],
       [-1, -1,  1],
       [-1, -1,  1]])

In [48]:
tot_w = w1+w2+w3

In [49]:
tot_w

array([[-3,  1,  1],
       [-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [ 1,  1,  1],
       [-1,  3, -1],
       [-1, -1, -1],
       [ 1,  1, -3],
       [ 1,  1, -3],
       [-1, -1, -1],
       [ 1,  1,  1],
       [ 1,  1, -3],
       [-1, -1, -1],
       [-3,  1,  1],
       [-1, -1, -1]])

# Forward Testing

In [50]:
y_1 = np.matmul(flat_a, tot_w)

In [51]:
y_2 = np.matmul(flat_b, tot_w)
y_3 = np.matmul(flat_c, tot_w)

In [68]:
def activation_fn(y_in):
    for i in range(0, 3):
        if y_in[0][i] >= 0:
            y_in[0][i] = 1
        elif y_in[0][i] < 0:
            y_in[0][i] = -1
    return y_in

In [69]:
y_out_1 = activation_fn(y_1)
y_out_2 = activation_fn(y_2)
y_out_3 = activation_fn(y_3)

In [70]:
y_out_1

array([[ 1, -1, -1]])

In [71]:
y_out_2

array([[-1, -1, -1]])

In [72]:
y_out_3

array([[-1, -1,  1]])

# Backward direction

In [74]:
x_1 = np.matmul(t1, np.transpose(tot_w))
x_2 = np.matmul(t2, np.transpose(tot_w))
x_3 = np.matmul(t3, np.transpose(tot_w))

In [77]:
def act_fn(x_in):
    for i in range(0, 15):
        if x_in[0][i] >= 0:
            x_in[0][i] = 1
        elif x_in[0][i] < 0:
            x_in[0][i] = -1
    return x_in

In [78]:
x_o_1 = act_fn(x_1)
x_o_2 = act_fn(x_2)
x_o_3 = act_fn(x_3)

In [79]:
x_o_1

array([[-1,  1,  1,  1, -1, -1,  1,  1,  1,  1, -1,  1,  1, -1,  1]])

In [80]:
x_o_2

array([[ 1,  1,  1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1]])

In [82]:
x_o_3

array([[ 1,  1,  1,  1, -1, -1,  1, -1, -1,  1, -1, -1,  1,  1,  1]])

# Testing with noise input

Orginal A

In [108]:
flat_a

array([[-1,  1,  1,  1, -1, -1,  1,  1,  1,  1, -1,  1,  1, -1,  1]])

In [104]:
test_1_a = np.array([[-1,  1,  1,  1, -1, -1,  1,  1,  1,  1, -1,  1,  -1, -1,  1]])

In [105]:
ty_1 = np.matmul(test_1_a, tot_w)

In [106]:
t_out_1 = activation_fn(ty_1)

In [107]:
t_out_1

array([[ 1, -1, -1]])