# Training

In [1]:
import numpy as np

In [2]:
p1 = np.array([[1, 0, 0, 0]])
p2 = np.array([[1, 1, 0, 0]])
p3 = np.array([[0, 0, 0, 1]])
p4 = np.array([[0, 0, 1, 1]])

t1 = np.array([[1, 0]])
t2 = np.array([[1, 0]])
t3 = np.array([[0, 1]])
t4 = np.array([[0, 1]])

In [3]:
t_p1 = np.transpose(p1)
t_p2 = np.transpose(p2)
t_p3 = np.transpose(p3)
t_p4 = np.transpose(p4)

In [4]:
w1 = np.matmul(t_p1, t1)
w2 = np.matmul(t_p2, t2)
w3 = np.matmul(t_p3, t3)
w4 = np.matmul(t_p4, t4)

In [5]:
tot_w = w1+w2+w3+w4
tot_w

array([[2, 0],
       [1, 0],
       [0, 1],
       [0, 2]])

# Testing

In [6]:
test1 = np.array([[1, 0, 0, 0]])

In [7]:
def activation_fun(net_op):
    for i in range(len(net_op)):
        for j in range(len(net_op[i])):
            if net_op[i][j] > 0:
                net_op[i][j] = 1
            else:
                net_op[i][j] = 0
    return net_op

In [8]:
net_op = np.matmul(test1,tot_w)
net_op

array([[2, 0]])

In [9]:
out_op = activation_fun(net_op)

In [10]:
out_op

array([[1, 0]])

In [11]:
test2 = np.array([[0, 1, 1, 0]])
net_op2 = np.matmul(test2, tot_w)
op2 = activation_fun(net_op2)
op2

array([[1, 1]])