In [1]:
import numpy as np

# Training

In [2]:
ip1 = np.array([[1, 1, 1],
      [1, -1, -1],
      [1, 1, 1],
      [1, -1, -1],
      [1, 1, 1]])

t1 = np.array([[-1, 1]])

In [3]:
ip1 = ip1.flatten()

In [6]:
ip1 = np.array([ip1])
ip1

array([[ 1,  1,  1,  1, -1, -1,  1,  1,  1,  1, -1, -1,  1,  1,  1]])

In [7]:
ip1.shape

(1, 15)

In [8]:
w1 = np.multiply((np.transpose(ip1)),t1)
w1

array([[-1,  1],
       [-1,  1],
       [-1,  1],
       [-1,  1],
       [ 1, -1],
       [ 1, -1],
       [-1,  1],
       [-1,  1],
       [-1,  1],
       [-1,  1],
       [ 1, -1],
       [ 1, -1],
       [-1,  1],
       [-1,  1],
       [-1,  1]])

In [12]:
ip2 = np.array([[1, 1, 1],
               [1, -1, -1],
               [1, 1, 1],
               [1, -1, -1],
               [1, -1, -1]])

ip2 = ip2.flatten()
ip2 = np.array([ip2])

In [13]:
t2 = np.array([[1, 1]])
w2 = np.multiply((np.transpose(ip2)),t2)
w2

array([[ 1,  1],
       [ 1,  1],
       [ 1,  1],
       [ 1,  1],
       [-1, -1],
       [-1, -1],
       [ 1,  1],
       [ 1,  1],
       [ 1,  1],
       [ 1,  1],
       [-1, -1],
       [-1, -1],
       [ 1,  1],
       [-1, -1],
       [-1, -1]])

In [14]:
tot_W = w1 + w2
tot_W

array([[ 0,  2],
       [ 0,  2],
       [ 0,  2],
       [ 0,  2],
       [ 0, -2],
       [ 0, -2],
       [ 0,  2],
       [ 0,  2],
       [ 0,  2],
       [ 0,  2],
       [ 0, -2],
       [ 0, -2],
       [ 0,  2],
       [-2,  0],
       [-2,  0]])

# Testing

In [15]:
test1 = np.array([[1, 1, 1],
                 [1, -1, -1],
                 [1, 1, 1],
                 [1, -1, -1],
                 [1, 1, 1]])
test1 = test1.flatten()
test1 = np.array([test1])

In [16]:
test1

array([[ 1,  1,  1,  1, -1, -1,  1,  1,  1,  1, -1, -1,  1,  1,  1]])

In [20]:
test1.dtype

dtype('int64')

In [21]:
tot_W.dtype

dtype('int64')

In [22]:
y1_in = np.matmul(test1, tot_W)
y1_in

array([[-4, 26]])

In [25]:
def activation_fun(net_op):
    for i in range(len(net_op)):
        for j in range(len(net_op[i])):
            if net_op[i][j] > 0:
                net_op[i][j] = 1
            else:
                net_op[i][j] = -1
    return net_op

In [26]:
op1 = activation_fun(y1_in)
op1

array([[-1,  1]])