In [1]:
import numpy as np

In [2]:
W = np.array([[0, 1, 1, -1],
             [1, 0, 1, -1],
             [1, 1, 0, -1],
             [-1, -1, -1, 0]])

In [3]:
W

array([[ 0,  1,  1, -1],
       [ 1,  0,  1, -1],
       [ 1,  1,  0, -1],
       [-1, -1, -1,  0]])

In [4]:
test_1 = np.array([0, 0, 1, 0])

In [5]:
test_1

array([0, 0, 1, 0])

In [6]:
update_order = [1, 4, 3, 2]

In [7]:
def hopfield_update(test_in, W, update_order):
    x = test_in
    y_in = test_in
    
    for i in update_order:
        y_net = np.matmul(y_in, W[:,i-1]) + x[i-1]
        
        if y_net >= 0:
            y_net = 1
        else:
            y_net = 0
            
        
        y_in[i-1] = y_net
        
        print("Updataion at ",i,"is ",y_in)

In [8]:
for i in update_order:
    print(W[:,i-1])

[ 0  1  1 -1]
[-1 -1 -1  0]
[ 1  1  0 -1]
[ 1  0  1 -1]


In [9]:
hopfield_update(test_1, W, update_order)

Updataion at  1 is  [1 0 1 0]
Updataion at  4 is  [1 0 1 0]
Updataion at  3 is  [1 0 1 0]
Updataion at  2 is  [1 1 1 0]
